### ISSUE TITLE
clousures.groovy

### ISSUE THREAD

**Issue by dmokrushin** [snowman80/groovy#2]
Please re-do without using sort, but implementing any kind of sorting yourself.

**Comment by snowman80** [comment]
new version pushed

**Comment by snowman80** [comment]
implemened closures, range

**Comment by dmokrushin** [comment]
Сортировка перестала быть сортировкой пузырьком, а стала несовсем осмысленными проходами по массиву. Сложность алгоритма в таком случае сильно выше.
