### ISSUE TITLE
files1.groovy

### ISSUE THREAD

**Issue by dmokrushin** [snowman80/groovy#4]
от 1 до 200 в каждой строке - This condition is not implemented in the code
line 9 - missing "def" 
new File("$path$name"+".txt") - part is with expression, part is with concatenation - should be in single manner. Investigate options of [new File(str1, str2)] constructor

**Comment by dmokrushin** [comment]
for (i=0; i<100000; i++)  - re-implement with range and each

**Comment by snowman80** [comment]
> от 1 до 200 в каждой строке - This condition is not implemented in the code
fixed (formula Random()*(b-a+a)+a))
> line 9 - missing "def"
fixed with range and each
> new File("$path$name"+".txt") - part is with expression, part is with concatenation - should be in single manner. Investigate options of [new File(str1, str2)] constructor
fixed

**Comment by dmokrushin** [comment]
(int)(Math.random()*200)+1 - это все-равно не от 1го до 200

for (i=0; i<100000; i++) - можно еще сделать в виде 10000.times {} попробуй такую конструкцию, это еще лучше читается

**Comment by snowman80** [comment]
corrected
