### ISSUE TITLE
matrix

### ISSUE THREAD

**Issue by dmokrushin** [snowman80/groovy#5]
def list1 = new File(path, 'file1.txt').collect {it}
def list2 = new File(path, 'file2.txt').collect {it}
def list3 = new File(path, 'file3.txt').collect {it}
def list4 = new File(path, 'file4.txt').collect {it}
def list5 = new File(path, 'file5.txt').collect {it}
def list6 = new File(path, 'file6.txt').collect {it}
def list7 = new File(path, 'file7.txt').collect {it}
def list8 = new File(path, 'file8.txt').collect {it}
def list9 = new File(path, 'file9.txt').collect {it}
def list10 = new File(path, 'file10.txt').collect {it}

too many variables, read to array of the files, also use reader and use BufferedReader  to read lines one by one.

**Comment by snowman80** [comment]
new version, but there is still an opportunity to improve
